stages:
  - Build
  - Run
  - Test
  - Stop
  
before_script:
  - docker info

build_image:
  stage: Build
  script:
#    First time
#    - docker run --rm --privileged multiarch/qemu-user-static:register
    - make build
    
#run_image:
#  stage: Run
#  script:
#    - make run-amd64

test_image:
  stage: Test
  script:
    - make test

stop_image:
  stage: Stop
  script:
    - docker stop $(docker ps -a -q)
    - docker rm $(docker ps -a -q)