image: docker:18.06.1-ce

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    
services:
    - docker:18.06.1-ce-dind

stages:
  - Install
  - Build
  - Run
  - Test
  - Stop
  
before_script:
    - docker info

install_qemu:
    tags:
        - docker
    stage: Install
    script:
        - make install
    allow_failure: true
    
build_image:
    tags:
        - docker
    stage: Build
    script:
        - make build
    
#run_image:
#  stage: Run
#  script:
#    - make run-amd64

#test_image:
#  stage: Test
#  script:
#    - make test

stop_image:
    tags:
        - docker
    stage: Stop
    script:
        - docker stop $(docker ps -a -q)
        - docker rm $(docker ps -a -q)
